src=com/company/opencvtest/JavaCam.java com/company/opencvtest/Dispatch.java  com/company/opencvtest/FramePkg.java
all:
	export LD_LIBRARY_PATH=/usr/lib/jni/; javac -classpath  ".:/usr/share/java/opencv-249.jar" $(src)
	export LD_LIBRARY_PATH=/usr/lib/jni/; java -classpath  ".:/usr/share/java/opencv-249.jar"  com/company/opencvtest/JavaCam
